export const HELP_TEXTS = {
  onboarding: 'Das Onboarding erfasst grundlegende Informationen über Ihr Unternehmen. Diese werden verwendet um die Verfahrensdokumentation zu personalisieren.',
  precheck: 'Die KI prüft Ihre Angaben auf Vollständigkeit und gibt Ihnen Hinweise falls wichtige Informationen fehlen.',
  chapter_approve: 'Nach der Freigabe wird dieses Kapitel als geprüft markiert und kann in die finale Verfahrensdokumentation übernommen werden.',
  chapter_submit: 'Mit dem Einreichen übermitteln Sie Ihre Angaben an Ihren Berater zur Prüfung. Sie können danach noch Änderungen vornehmen.',
  generate_text: 'Die KI erstellt basierend auf Ihren Angaben und den Onboarding-Daten einen professionellen GoBD-konformen Text für dieses Kapitel.',
  editor_text: 'Der Editor-Text ist die endgültige Fassung des Kapitels, die in die Verfahrensdokumentation übernommen wird.',
  client_notes: 'Beschreiben Sie hier die relevanten Informationen für dieses Kapitel. Orientieren Sie sich an den Leitfragen.',
  document_preview: 'Die Vorschau zeigt die Verfahrensdokumentation so, wie sie im finalen PDF aussehen wird.',
  document_create: 'Erstellt eine neue Version der Verfahrensdokumentation als PDF. Diese wird automatisch heruntergeladen.',
  plan_limits: 'Das Mandanten-Limit zählt alle jemals angelegten Mandanten, auch gelöschte. Durch Löschen wird kein Kontingent frei.',
  soft_delete: 'Mandanten mit finalisierten Dokumenten können nicht gelöscht werden. Gelöschte Mandanten werden nur deaktiviert, nicht entfernt.',
  webhook: 'Webhooks ermöglichen die automatische Benachrichtigung externer Systeme bei bestimmten Ereignissen.',
  branding: 'Passen Sie das Erscheinungsbild für Ihre Mandanten an: Logo, Farben und Kontaktinformationen.',
  affiliate: 'Empfehlen Sie die GoBD-Suite weiter und erhalten Sie eine Provision für neue Lizenznehmer.',
  team: 'Laden Sie Teammitglieder ein und verwalten Sie deren Zugriffsrechte.',
  trial_period: 'Neue Lizenznehmer erhalten eine kostenlose Testphase. Nach Ablauf muss ein Plan gewählt werden.',
  billing: 'Hier sehen Sie Ihren aktuellen Plan, Ihre Nutzung und können ein Upgrade anfragen.',
  data_export: 'Exportiert alle Ihre personenbezogenen Daten als ZIP-Archiv. Der Link ist 24 Stunden gültig.',
  data_deletion: 'Nach Bestätigung werden alle personenbezogenen Daten anonymisiert. Verfahrensdokumentationen bleiben für die Aufbewahrungspflicht erhalten.',
  session_timeout: 'Aus Sicherheitsgründen werden Sie nach einer Periode der Inaktivität automatisch abgemeldet.',
  two_factor: 'Zwei-Faktor-Authentifizierung erhöht die Sicherheit Ihres Kontos durch einen zusätzlichen Code bei der Anmeldung.',
  notifications: 'Hier sehen Sie Benachrichtigungen zu eingereichten Kapiteln, Freigaben und anderen wichtigen Ereignissen.',
  consent_gdpr: 'Mit der Zustimmung bestätigen Sie, dass Sie die Datenschutzerklärung gelesen haben und mit der Verarbeitung Ihrer Daten einverstanden sind.',
} as const;
