[functions.precheck-chapter-notes]
verify_jwt = false

[functions.generate-chapter-text]
verify_jwt = false

[functions.create-client-user]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = false

[functions.invite-client]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false


[functions.send-notification]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.invite-tenant]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.funnelpay-webhook]
verify_jwt = false

[functions.create-trial-account]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.send-support-notification]
verify_jwt = false

[functions.send-support-reply]
verify_jwt = false

[functions.receive-support-reply]
verify_jwt = false
